import "@reach/dialog/styles.css"
import "firebase/auth"
import "firebase/firestore"
import "firebase/functions"
import "firebaseui/dist/firebaseui.css"
import "prismjs/themes/prism-okaidia.css"
import "./src/styles/global.scss"
import "./src/styles/index.css"
